name: mesh-seg-gpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1
  - matplotlib
  - numpy
  - pytorch=1.9.0
  - python=3.7.12
  - pip
  - tensorboard
  - trimesh
