name: mesh-seg-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - matplotlib
  - numpy
  - pytorch
  - python=3.7
  - pip
  - trimesh
  - pip:
    - torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
    - torch-geometric
